from enum import Enum

class Markets(Enum):
    MONEYLINE = 1
    POINT_SPREAD = 2
    OVER_UNDER = 3
    FUTURES = 4
    PARLAYS = 5
    TEASERS = 6
    PLAYER_REBOUNDS = 7
    PLAYER_POINTS = 8
    PLAYER_ASSISTS = 9
    PLAYER_STEALS = 10
    PLAYER_BLOCKS = 11
    PLAYER_TURNOVERS = 12
    PLAYER_FOULS = 13
    PLAYER_FREE_THROWS = 14
    PLAYER_THREE_POINTERS = 15
    TEAM_REBOUNDS = 16
    TEAM_POINTS = 17
    TEAM_ASSISTS = 18
    TEAM_STEALS = 19
    TEAM_BLOCKS = 20
    TEAM_TURNOVERS = 21
    TEAM_FOULS = 22
    TEAM_FREE_THROWS = 23
    TEAM_THREE_POINTERS = 24
    IN_PLAY_BETTING = 25
    HANDICAP = 26
    EXACT_SCORE = 27
    FIRST_HALF_SECOND_HALF = 28
    ODD_EVEN = 29
    RACE_TO_POINTS = 30
    MARGIN_OF_VICTORY = 31
    TEAM_TOTALS = 32